name: forgetit
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.4+4

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  change_app_package_name: ^1.3.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  image: ^4.2.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  package_info_plus: ^8.0.0
  path: ^1.9.0
  path_provider: ^2.1.3
  sqflite: ^2.3.3+1
  sqflite_common_ffi: ^2.3.3
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: "ic_launcher"
  ios: false
  image_path: "assets/logo.png"
  min_sdk_android: 21
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false
